name: CD

on:
  push:
    branches: [ main ]

jobs:
  job_1:
    name: publish to VSM
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn install
    - run: yarn cd:publish
      env:
        VSCE_PAT: ${{secrets.VSCE_TOKEN}}